# services/api/Dockerfile
FROM public.ecr.aws/lambda/python:3.11
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY services/api /var/task
# handler will be provided by awslambdaric when we wire ASGI adapter
